djangosweng/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

from django.views.generic.base import TemplateView


urlpatterns = [
    path('admin/', admin.site.urls),    # points to django admin pages
    path('', include('rentalsystem.urls')),
    path('accounts/', include('django.contrib.auth.urls')),  # points to django's auth module urls
]

if settings.DEBUG: #add only in debug mode
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

rentalsystem/urls.py
from django.urls import path

from . import views
from django.views.generic.base import TemplateView

urlpatterns = [
    path('', views.home, name='home'),
    path('signup/', views.SignUp.as_view(), name='signup'),
    path('home/', views.home, name='home'),
    path('about/', views.about, name = 'about'),
    path('landing/', views.landing, name='landing'),
    path('myjobs/', views.myjobs, name='myjobs'),
    path('my_orders/', views.my_orders, name='my_orders'),
    path('profile/', views.profile, name='profile'),
    path('home_search/', views.home_search, name='home_search'),
    path('jobstats/', views.jobstats, name='jobstats'),
    path('postItem/', views.user_post_item, name='user_post_item'),
    path('item_details/', views.post_item_details, name="item_details"),
    path('post_item_complete/', views.post_item_complete, name="post_item_complete"),
    path('leave_review/',views.leave_review, name="leave_review"),
    path('create_transaction/', views.createTrans, name='create_transaction'),
    path('item_listings/', views.item_listings, name='item_listings'),
    path('review_confirmation/',views.review_confirmation, name="review_confirmation"),
    path('confirm_transaction/', views.confirm_transaction, name='confirm_transaction'),
    path('edit_account/', views.account_settings, name='edit_account'),
    path('rent_item/', views.rent_item, name='rent_item'),
    path('account_details/', views.account_details, name='account_details'),
    path('leave/', views.profile, name='leave'),
    path('upload_pic/', views.upload_pic, name='upload_pic'),
    path('my_listings/', views.my_listings, name='my_listings'),
    path('cron/',views.updateiteminfo, name='cron'),
    path('confirm_return/', views.confirm_return, name='confirm_return'),
]

rentalsystem/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.urls import reverse
from django.core.validators import MaxValueValidator, MinValueValidator

# stores addresses for customers
class Address(models.Model):
    # user = models.ForeignKey(CustomUser, on_delete=models.PROTECT, db_column='CustomUser_id')
    address1 = models.CharField(max_length=200, blank=True, null=True)
    address2 = models.CharField(max_length=200, blank=True, null=True)
    address3 = models.CharField(max_length=200, blank=True, null=True)
    address4 = models.CharField(max_length=200, blank=True, null=True)
    address5 = models.CharField(max_length=200, blank=True, null=True)
    # county = models.CharField(max_length=100)
    post_code = models.CharField(max_length=20, blank=True, null=True)

    def __str__(self):
        return self.post_code

# subclassing django's default user class to make our own user class - AbstractUser superclass contains all the
# password and session magic we need
class CustomUser(AbstractUser):
    # tuple list stores the different roles a user can have
    ROLE_TYPES = (
        ('C', 'Customer'),
        ('S', 'Staff'),
        ('A', 'Admin'),
    )
    address =  models.ForeignKey(Address, on_delete=models.PROTECT, db_column='address_id', blank=False, null=False, default=1)  # foreign key to Category
    role = models.CharField(max_length=50, choices=ROLE_TYPES, default='C')  # stores customer/staff/admin role
    region = models.CharField(max_length=100)               # stores region
    name = models.CharField(max_length=100)                 # stores full name of user
    job_capacity = models.IntegerField(blank=True, null=True)          # STAFF ONLY: number of jobs they can do per day
    card_long_number = models.BigIntegerField(blank=True, null=True)      # CUSTOMER ONLY: payment card long number
    card_expiry_date = models.DateField(blank=True, null=True)         # CUSTOMER ONLY: payment card expiry date
    card_cvv = models.IntegerField(blank=True, null=True)              # CUSTOMER ONLY: payment card cvv code

    def __str__(self):
        return self.email



class Profile(models.Model):
    user = models.OneToOneField(CustomUser, on_delete=models.CASCADE)
    image = models.ImageField(default='default.jpg', upload_to='profile_pics')

    def __str__(self):
        return f'{self.user.name} Profile'

# category class
class Category(models.Model):
    title = models.CharField(max_length=100)                # holds the title of the category
    description = models.CharField(max_length=500)          # holds the description of the category

    def __str__(self):
        return self.title


# item class
class Item(models.Model):
    name = models.CharField(max_length=100)                 # Name of generic item
    info = models.CharField(max_length=5000, blank=True)     # description of item
    image = models.ImageField(default='default.jpg', upload_to='item_pics')
    average_rating = models.IntegerField(blank=True, null=True) 
    lowest_cost = models.IntegerField(blank=True, null=True) 
    def get_absolute_url(self):
        return reverse('post_item_details', kwargs={'pk': self.pk})

    def __str__(self):
        return self.name


# Item category link, item can have multiple category pairs
class ItemCategoryPair(models.Model):
    item_id = models.ForeignKey(Item, on_delete=models.PROTECT, db_column='item_id')  # foreign key to Category
    category_id = models.ForeignKey(Category, on_delete=models.PROTECT, db_column='category_id')  # foreign key to Category


# item listing class
class ItemListing(models.Model):
    title = models.CharField(max_length=100)                    # Title for item listing
    additional_info = models.CharField(max_length=500, blank=True)     # optional description of item listed
    cost_per_day = models.PositiveIntegerField()            # holds the cost per day, must be positive
    owner_id = models.ForeignKey(CustomUser, on_delete=models.PROTECT, db_column='owner_id')  # foreign key to CustomUser
    item_type_id = models.ForeignKey(Item, on_delete=models.PROTECT, db_column='item_type_id') # foreign key to Item

    def __str__(self):
        return self.title

# transaction class
class Transaction(models.Model):
    item_id = models.ForeignKey(ItemListing, on_delete=models.PROTECT, db_column='item_id') # foreign key to Item
    owner_id = models.ForeignKey(CustomUser, on_delete=models.PROTECT, related_name='owner_id')
    renter_id = models.ForeignKey(CustomUser, on_delete=models.PROTECT, related_name='renter_id')
    total_cost = models.PositiveIntegerField()
    start_date = models.DateField()
    end_date = models.DateField(blank = True, null = True)


# job list class
class JobList(models.Model):
    staff_id = models.ForeignKey(CustomUser, on_delete=models.PROTECT, db_column='staff_id')


# job class
class Job(models.Model):
    transaction_id = models.ForeignKey(Transaction, on_delete=models.PROTECT, db_column='transaction_id', null=True)
    job_list_id = models.ForeignKey(JobList, on_delete=models.PROTECT, db_column='job_list_id', blank=True, null=True)
    due_delivery_datetime = models.DateTimeField()
    delivered_datetime = models.DateTimeField(blank=True, null=True)
    address1 = models.CharField(max_length=200, blank=True, null=True)
    address2 = models.CharField(max_length=200, blank=True, null=True)
    address3 = models.CharField(max_length=200, blank=True, null=True)
    address4 = models.CharField(max_length=200, blank=True, null=True)
    address5 = models.CharField(max_length=200, blank=True, null=True)
    county = models.CharField(max_length=100)
    post_code = models.CharField(max_length=20, blank=True, null=True)


# dispute class
class Dispute(models.Model):
    transaction_id = models.ForeignKey(Transaction, on_delete=models.PROTECT, db_column='transaction_id')
    content = models.CharField(max_length=500, blank=True, null=True)
    resolved = models.BooleanField(default=False)


# payment class
class Payment(models.Model):
    transaction_id = models.ForeignKey(Transaction, on_delete=models.PROTECT, db_column='transaction_id')
    user_id = models.ForeignKey(CustomUser, on_delete=models.PROTECT, db_column='user_id')
    payment_amt = models.PositiveIntegerField()
    payment_date = models.DateTimeField()


# reviews class
class Reviews(models.Model):
    # review can be left for either a transaction or a customer? not sure what we wanna do here
    transaction_id = models.ForeignKey(Transaction, on_delete=models.PROTECT, db_column='transaction_id')
    content = models.CharField(max_length=500)
    item_rating = models.PositiveIntegerField(
        default = 3,
        validators=[
            MaxValueValidator(5),
            MinValueValidator(1)
        ])
    transaction_rating = models.PositiveIntegerField(
        default = 3,
        validators=[
            MaxValueValidator(5),
            MinValueValidator(1)
        ])
    left_by_user_id = models.ForeignKey(CustomUser, on_delete=models.PROTECT, db_column='left_by_user_id')

rentalsystem/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.contrib.auth.models import User
from .models import CustomUser, Address
from django import forms



# a form which extends the built-in Django UserCreationForm - required because we're overriding the built in User, so
# we need to define a new Meta class to tell it to use the CustomUser model
class CustomUserCreationForm(UserCreationForm):

    class Meta(UserCreationForm):
        model = CustomUser
        fields = ('username', 'email', 'region', 'name')


# a form which extends the built-in Django UserChangeForm - required because we're overriding the built in User, so
# we need to define a new Meta class to tell it to use the CustomUser model
class CustomUserChangeForm(UserChangeForm):

    class Meta:
        model = CustomUser
        fields = ('username', 'email')


class DateForm(forms.Form):
    date = forms.DateField(input_formats=['%Y/%m/%d'])

class ImageUploadForm(forms.Form):
    """Image upload form."""
    image = forms.ImageField()

rentalsystem/templates/rentalsystem/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">


<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>BorrowPeoplesStuff.com</title>

  <!-- CSS -->
  <link rel="stylesheet" href="{% static 'css/style.css' %}">


  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>



    <!-- jQuery -->
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>

  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="//netdna.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css">
  <!-- Bootstrap core CSS -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
        integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

  <!-- Icons fontawesome -->
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">

      <!-- Datepicker -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/datepicker/0.6.5/datepicker.min.css" integrity="sha256-b88RdwbRJEzRx95nCuuva+hO5ExvXXnpX+78h8DjyOE=" crossorigin="anonymous" />
  <script src="https://cdnjs.cloudflare.com/ajax/libs/datepicker/0.6.5/datepicker.min.js" integrity="sha256-/7FLTdzP6CfC1VBAj/rsp3Rinuuu9leMRGd354hvk0k=" crossorigin="anonymous"></script>


</head>

<body>


  <!-- Navigation -->
  <nav class="fixed-top navbar navbar-expand-lg navbar-dark bg-dark static-top mb-32">
    <div class="container">
      <a class="navbar-brand" href="{%  url 'home' %}">BorrowPeoplesStuff</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item active">
            <a class="nav-link" href="{%  url 'home' %}">Home
              <span class="sr-only">(current)</span>
            </a>
          </li>
            {% if user.role ==  'S' %}
                <li class="nav-item">
                    <p><a class="nav-link" href="{% url 'myjobs' %}">My Jobs</a></p>
                </li>
            {% endif %}
            {% if user.role ==  'A' %}
                <li class="nav-item">
                  <button class="btn btn-sm btn-primary"><a class="nav-link text-white" href="{% url 'cron' %}">cron</a></button>
                </li>
                <li class="nav-item">
                    <p><a class="nav-link" href="{% url 'jobstats' %}">Job Stats</a></p>
                </li>
                <li class="nav-item">
                    <p><a class="nav-link" href="/admin/">Admin</a></p>
                </li>
            {% endif %}
            {% if user.is_authenticated %}
                <li class="nav-item" style="border-left: 1px solid rgb(78, 77, 77);">
                    <p><a class="nav-link" href="{% url 'user_post_item' %}">Upload Game</a></p>
                </li>
                <li class="nav-item">
                    <p><a class="nav-link" href="{% url 'my_listings' %}">My Listings</a></p>
                </li>
                <li class="nav-item">
                    <p><a class="nav-link" href="{% url 'my_orders' %}">My Orders</a></p>
                </li>
            {% endif %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'about' %}">About</a>
          </li>
            {%  if user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link" href="{%  url 'profile' %}">Profile</a>
          </li>
          <li class="nav-item">
            <p><a class="nav-link" href="{% url 'logout' %}">Logout</a></p>
          </li>
            {%  else %}
                <li class="nav-item">
            <a class="nav-link" href="{% url 'login' %}">Login</a>
          </li>
          <li class="nav-item">
            <p><a class="nav-link" href="{% url 'signup' %}">Register</a></p>
          </li>
            {%  endif %}
        </ul>

      </div>


    </div>
  </nav>






  <!-- Page Content -->
  <div class="container mt-128 mb-128" >
        {%  block content %}{% endblock %}
  </div>

  <footer class="fixed-bottom footer center-text">
    <div class="footer-copyright text-center">© 2019 Copyright:
         <a href="{% url 'home' %}"> BorrowPeoplesStuff.com</a>

      <p> @BorrowPeoplesStuff</p>
      <p>www.support@BorrowPeoplesStuff.com</p>
    </div>

  </footer>

</body>

</html>

rentalsystem/templates/rentalsystem/confirm_transaction.html
{% extends 'rentalsystem/base.html' %}

{% block title %}Confirm transaction{% endblock %}

{% block content %}


<div class="container-fluid white-container">
  <h2 class="text-center text-info">Almost there</h2><br>
	<div class="row">
		<div class="col-md-3">
        <img class="card-img-top" src="{{ list_details.item_type_id.image.url }}" >
		</div>
		<div class="col-md-9">
        <table class="table border-bottom">
            <tr>
                <th>ID</th>
                <th>Item</th>
                <th>Total Cost</th>
                <th>From</th>
                <th>To</th>
                <th>Owner</th>
            </tr>
            <tr>
                <td> {{ list_details.id }} </td>
                <td> {{ list_details.title }} </td>
                <td> £{{ cost }} </td>
                <td> {{ dates.0 }} </td>
                <td> {{ dates.1}} </td>
                <td> {{ list_details.owner_id.name }} </td>
            </tr>

        </table>
        <h5>Additional info</h5>
        <div class="container-fluid bg-light ">

            <div class="col-lg-12 " style="padding: 20px;" >
              {{list_details.additional_info}}
            </div>
        </div>

        <!-- create transaction -->
        <form class="" action="/rent_item/" method="post">
          {% csrf_token %}
          <input type="hidden" name="start_date" value="{{dates.0}}">
          <input type="hidden" name="end_date" value="{{dates.1}}">
          <input type="hidden" name="listing_id" value="{{ list_details.id }}">
          <input type="hidden" name="owner_id" value="{{ list_details.owner_id.id }}">
          <input type="hidden" name="total_cost" value="{{ cost }}">

          <button class="btn btn-primary btn-sm rent-btn" style="right: 15px; position: absolute; padding: 10px; width: 96%">Rent</button>
        </form>

		</div>


	</div>
</div>







{% endblock %}

rentalsystem/templates/rentalsystem/create_transaction.html
{% extends 'rentalsystem/base.html' %}

{% block title %}Home{% endblock %}

{% block content %}

<h2> {{list_details.item_type_id.name}}</h2>

                <form action='/create_transaction/' method='POST'>
                    {% csrf_token %}
                    <p>Start Date: </p>
{#                    <input type="date" class="form-control" id="date" value="{{placement.date|date:"Y-m-d" }}">#}
                        <input id="StartDate" name="date" value="">
                    <p>End Date: </p>
{#                    <input id="EndDate" name="date2" value="{{placement.date|date:"Y-m-d" }}" >#}
                        <input id="EndDate" name="date1" value="">
                        <p>Cost per day: </p>
                    <input id="Cost" name="cost" >
                    <button class="btn btn-success center-block" value="Submit">Submit</button>
                </form>

    <h4>{{info}}</h4>
        <h4>{{info1}}</h4>
    <h4>{{info2}}</h4>

  <script>
    $(function () {
      $("#StartDate").datepicker({
          format: 'yyyy-mm-dd',
      });
    });
  </script>
  <script>
    $(function () {
      $("#EndDate").datepicker({
          format: 'yyyy-mm-dd',
      });
    });
  </script>

{% endblock %}

rentalsystem/templates/rentalsystem/edit_account.html
{% extends 'rentalsystem/base.html' %}

{% block title %}Home{% endblock %}

{% block content %}

    <h2> {{ list_details.item_type_id.name }}</h2>
    <style>
        .asd {
            position: relative;
            margin-top: 50px;
            width: 500px;
            height: 300px;
        }

        .fagg {
            position: absolute;
            top: 0;
            left: 0;
            background: rgba(0, 0, 0, 0);
            transition: background 0.5s ease;
        }

        .asd:hover .overlay {
            display: block;
            background: rgba(0, 0, 0, .3);
        }


        .asd:hover .title {
            top: 90px;
        }

        .button {
            position: absolute;
            width: 500px;
            left: 110px;
            top: 180px;
            text-align: center;
            opacity: 0;
            transition: opacity .35s ease;
        }

        .button a {
            font-weight: bold;
            font-size: 20px;
            width: 200px;
            padding: 12px 48px;
            text-align: center;
            color: black;
            border: solid 2px black;
            z-index: 1;
            background: #f90;
        }

        .asd:hover .button {
            opacity: 1;
        }

        .asda {
            top: 500px;
            position: absolute;
            width: 500px;
            right: 200px;
            text-align: center;
        }


    </style>

    <div class="container">
        <div class="row">
            <div class="col-sm">

                <form action='/upload_pic/' method="post" enctype="multipart/form-data">{% csrf_token %}
                    <p>
                    <div class="asd">
                        <img class="fagg card rounded-circle account-img" style="width:400px"
                             src="{{ user.profile.image.url }}">
                        <input id="id_image" type="file" class="button" name="image" value="pick">
                    </div>
                    </p>
                    <div class="asda">
                        <input class="btn btn-success center-block" type="submit" value="Change picture"/>
                    </div>
                </form>

            </div>
            <div class="col-sm">
                <form action='/account_details/' method='POST'>
                    {% csrf_token %}
                    <p><b>Username</b></p>
                    <input id="StartDate" name="username" value={{ user.username }}>
                    <P></P>
                    <p><b>Email</b></p>
                    <input id="EndDate" name="email" value={{ user.email }}>
                    <P></P>
                    <p><b>Address</b></p>
                    <p>{{ user.address.address1 }}</p>
                    <p>{{ user.address.address2 }}</p>
                    <p>{{ user.address.post_code }}</p>
                    <input id="Costl" name="adline1"><br>
                    <input id="Costl" name="adline2"><br>
                    <input id="Costl" name="adline3"><br>
                    <P></P>
                    <p><b>Region</b></p>
                    <input id="Costl" name="region" value={{ user.region }}>
                    <P></P>
                    <p><b>Card number</b></p>
                    <input id="Costfg" name="Card number" value={{ user.card_long_number }}>
                    <P></P>
                    <p><b>Card expiry date</b></p>
                    <p>{{ user.card_expiry_date }}</p>
                    <input id="Costd" type="date" name="Card expiry date">
                    <P></P>
                    <p><b>Card cvv</b></p>
                    <input id="Costa" name="Card cvv" value={{ user.card_cvv }}>
                    <P></P>
                    <button class="btn btn-success btn-lg center-block" value="Submit">Submit</button>
                    <P></P>
                </form>
                <form action='/leave/' method='POST'>
                    {% csrf_token %}
                    <button class="btn btn-danger btn-lg center-block">Leave</button>
                </form>


            </div>
        </div>
    </div>
    {% if controller == True %}
        <script>alert("Pick an image first");</script>{% endif %}




{% endblock %}

rentalsystem/templates/rentalsystem/home.html
{% extends 'rentalsystem/base.html' %}

{% block title %}Home{% endblock %}

{% block content %}
 <!-- Page Content -->
  <div class="container">

    <div class="row">

      <div class="col-lg-3">

        <h1 class="my-4">Categories</h1>

        <div class="list-group mb-32">

          <form class="searchBar" action="/home_search/" method="get">
            <input type="text" name="search_query" placeholder="Search">
            <button type="submit" value="Search"><i class="fas fa-search"></i></button>
          </form>

            {% for category in categories %}
            <!--<a href="" class="list-group-item">{{ category }}</a> -->
            <form  action='/home_search/' method='POST'>
                {% csrf_token %}
                <input type="hidden" name="catPk" value="{{category.id}}">
                <button class="btn-outline-secondary btn-sm btn-block">{{category}}</button>
            </form>
            {%  endfor %}
        </div>

      </div>
      <!-- /.col-lg-3 -->

      <div class="col-lg-9">


        <div class="row">
            {%  for item in items %}
          <div class="col-lg-4 col-md-6 mb-4">
            <div class="card h-100">
              <a href="/item_listings?query_name={{ item|urlencode }}"><img class="card-img-top" src="{{ item.image.url }}" height="200" width="auto"></a>
              <div class="card-body">
                <h4 class="card-title">
                  <a href="/item_listings?query_name={{ item|urlencode }}">{{ item }}</a>
                </h4>
                  {% if item.lowest_cost != None %}
                    <h5 class="text-success">£{{item.lowest_cost}}</h5>
                  {% else %}
                    <h5 class="text-danger">Currently Out Of Stock</h5>
                  {% endif %}
              <div class="card-title">
                      {% if item.average_rating == 0 %}
                          <i>Not Rated</i>
                      {% endif %}
                      {% if item.average_rating == 1 %}
                          <span class="fa fa-star" style="color:orange"></span>
                          <span class="fa fa-star"></span>
                          <span class="fa fa-star"></span>
                          <span class="fa fa-star"></span>
                          <span class="fa fa-star"></span>
                      {% endif %}
                      {% if item.average_rating == 2%}
                          <span class="fa fa-star" style="color:orange"></span>
                          <span class="fa fa-star" style="color:orange"></span>
                          <span class="fa fa-star"></span>
                          <span class="fa fa-star"></span>
                          <span class="fa fa-star"></span>
                      {% endif %}
                      {% if item.average_rating == 3%}
                          <span class="fa fa-star" style="color:orange"></span>
                          <span class="fa fa-star" style="color:orange"></span>
                          <span class="fa fa-star" style="color:orange"></span>
                          <span class="fa fa-star"></span>
                          <span class="fa fa-star"></span>
                      {% endif %}
                      {% if item.average_rating == 4%}
                          <span class="fa fa-star" style="color:orange"></span>
                          <span class="fa fa-star" style="color:orange"></span>
                          <span class="fa fa-star" style="color:orange"></span>
                          <span class="fa fa-star" style="color:orange"></span>
                          <span class="fa fa-star"></span>
                      {% endif %}
                      {% if item.average_rating == 5 %}
                          <span class="fa fa-star" style="color:orange"></span>
                          <span class="fa fa-star" style="color:orange"></span>
                          <span class="fa fa-star" style="color:orange"></span>
                          <span class="fa fa-star" style="color:orange"></span>
                          <span class="fa fa-star" style="color:orange"></span>
                      {% endif %}
              </div>

              <div style="overflow-y: auto; height: 150px">
                <p class="card-text">{{ item.info }}</p>
              </div>

              </div>
            </div>
          </div>
            {%  endfor %}
        </div>
        <!-- /.row -->

      </div>
      <!-- /.col-lg-9 -->

    </div>
    <!-- /.row -->

  </div>
  <!-- /.container -->
{% endblock %}

rentalsystem/templates/rentalsystem/item_form.html
{% extends 'rentalsystem/base.html' %}

{% block title %}Add Item{% endblock %}

{% block content %}

    <div class="container">
        <div class="row">
            <form class="form-horizontal" method="post"  enctype="multipart/form-data">
                {% csrf_token %}
                {% for field in form %}
                    <div class="form-group">
                        <div class="col-sm-offset-2 col-sm-10">
                            <span class="text-danger small">{{ field.errors }}</span>
                        </div>
                    <label class="control-label col-sm-2">{{ field.label_tag }}</label>
                    <div class="col-sm-10">{{ field }}</div>
                    </div>
                {% endfor %}
                <div class="form-group">
                    <div class="col-sm-offset-2 col-sm-10">
                        <input type="submit" value="Submit" class="btn btn-success">
                    </div>
                </div>
            </form>
        </div>

    </div>

{% endblock %}

rentalsystem/templates/rentalsystem/landing.html
{% extends 'rentalsystem/base.html' %}

{% block title %}Home{% endblock %}

{% block content %}
  <p>You are not logged in</p>
  <a href="{% url 'login' %}">Login</a> or <a href="{% url 'signup' %}">Sign up</a>


{% endblock %}
\ No newline at end of file